vote14: Game Interruption procedure
RoboCup-Humanoid-TC/Rules pull request #25
Opened 2022-01-29 17:27 UTC by babaev1

The procedure for handling game interruptions was clarified in the virtual rule book. In particular, it was decided where exactly the ball shall be placed and what happens to robots that are already penalized but closer to the ball than they are allowed to. The same procedure could be applied to the physical rules.

2022-02-02 13:32 UTC, MaikePaetzel requested changes

2022-02-02 13:32 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +\item The referee \removed{blows the whistle,} announces the offence and the
keep the "blows the whistle", but add (in the physical competition)

2022-02-02 13:32 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +    awarded to the game controller.}
Add: "or the assistant referee operating the game controller in a physical competition.

2022-02-02 13:32 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +        GameController.%
Add: "or the assistant referee operating the game controller in a physical competition."

2022-02-02 13:32 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +        the GameController}.%
Add: "or the assistant referee operating the game controller. In case of a physical competition, the referee additionally blows the whistle."

2022-02-06 06:35 UTC, babaev1 commented
Resolved

  
>Среда, 2 февраля 2022, 16:32 +03:00 от MaikePaetzel ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>>  
> \begin{enumerate}
>-\item The referee blows the whistle, announces the offence and the free kick
>+\item The referee \removed{blows the whistle,} announces the offence and the
>
>keep the "blows the whistle", but add (in the physical competition)
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>>        (e.g 'Pushing Red - Direct Free-Kick Blue')
>-\item The assistant referee who operates the game controller clicks on "Direct / Indirect Free Kick" Blue/Red.
>-\item The referee places the ball depending on the call and announces "Free Kick Ready".
>+\item \removed{The assistant referee who operates the game controller clicks on
>+    "Direct / Indirect Free Kick" Blue/Red.}
>+  \added{The referee communicates the game interruption and to which team it is
>+    awarded to the game controller.}
>
>Add: "or the assistant referee operating the game controller in a physical competition.
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>> +          referee tries to find a nearby location for the ball that is at a
>+          distance of at least $D$ from all objects.
>+          This location should respects the rule for the game interruption.
>+          In particular, there are no alternative location for penalties, goal
>+          kicks and corner kicks.
>+        \item If previous steps were not sufficient, the remaining robots
>+          at a distance of less than $D$ from the ball location are moved away
>+          from the ball, ensuring that they are at least at a distance of $D$
>+          from all objects, including the ball.
>+        \end{enumerate}
>+      }
>+\item \removed{The assistant referee who operates the game controller clicks on
>+        "Prepare Direct / Indirect Free Kick" Blue/Red.}
>+      \added{%
>+        The referee communicates that the Game Interruption is ready to the
>+        GameController.%
>
>Add: "or the assistant referee operating the game controller in a physical competition."
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>>        legally positioned or have been removed from the field,
>-      the referee blows the whistle.
>-      Then the assistant referee who operates the game controller clicks on
>-      "Execute Direct / Indirect Free Kick" Blue/Red.
>-      The team that was awarded the free-kick can kick now.
>+      \added{the referee announces that the game interruption can be executed to
>+        the GameController}.%
>
>Add: "or the assistant referee operating the game controller. In case of a physical competition, the referee additionally blows the whistle."
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <RoboCup-Humanoid-TC/Rules/pull/25/review/870536652 @ github . com> 
 
 
--
A B
Отправлено из Почты  Mail.ru
 

2022-02-07 12:37 UTC, MaikePaetzel commented
I don't see the commit that resolves these issues?

2022-02-24 17:54 UTC, MaikePaetzel commented
According to the rule voting G01Q14, this PR was accepted. However, as this was already added to the rule book by the general merge PR, this particular PR will still not be merged in but it will be clarified that this holds for both the physical and virtual competition.

2022-02-24 17:54 UTC, closed without merging