vote15: Penalty Shoot-out
RoboCup-Humanoid-TC/Rules pull request #26
Opened 2022-01-29 17:35 UTC by babaev1

For the virtual rule book, we clarified the consequences of committing certain fouls during a penalty shoot-out. The same procedure could be applied to the physical rule book.

2022-02-02 13:24 UTC, MaikePaetzel requested changes

2022-02-02 13:24 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +\item Both players are spawned at appropriate locations.
Both players are placed or spawned at appropriate locations.

2022-02-02 13:24 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +\item Ball is spawned on the penalty mark.
The ball is placed or spawned...

2022-02-02 13:24 UTC, MaikePaetzel commented on Section_II/competition_and_trophies.tex
> +\item The referee waits 15 seconds before sending signals to start the trial
The referee waits 15 seconds before starting the trial

2022-02-06 06:34 UTC, babaev1 commented
Resolved

  
>Среда, 2 февраля 2022, 16:24 +03:00 от MaikePaetzel ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>> @@ -346,7 +346,34 @@
> 
> 
> \bigskip
>+\added{
>+{\bfseries Penalty shoot-outs procedure}
>+
>+The referee decides randomly towards which goal the penalty shoot-outs will be
>+performed.
>+Then, each penalty trial is performed with the following procedure.
>+ 
>+\begin{enumerate}
>+\item The striker is defined as the robot from the striker's team with the
>+  lowest ID without a red card.
>+\item The goalkeeper is chosen based on the GameController information.
>+\item Both players are spawned at appropriate locations.
>
>Both players are placed or spawned at appropriate locations.
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>> @@ -346,7 +346,34 @@
> 
> 
> \bigskip
>+\added{
>+{\bfseries Penalty shoot-outs procedure}
>+
>+The referee decides randomly towards which goal the penalty shoot-outs will be
>+performed.
>+Then, each penalty trial is performed with the following procedure.
>+ 
>+\begin{enumerate}
>+\item The striker is defined as the robot from the striker's team with the
>+  lowest ID without a red card.
>+\item The goalkeeper is chosen based on the GameController information.
>+\item Both players are spawned at appropriate locations.
>+\item State is set to SET
>+\item Ball is spawned on the penalty mark.
>
>The ball is placed or spawned...
>----------------------------------------------------------------------
>In  Section_II/competition_and_trophies.tex :
>> @@ -346,7 +346,34 @@
> 
> 
> \bigskip
>+\added{
>+{\bfseries Penalty shoot-outs procedure}
>+
>+The referee decides randomly towards which goal the penalty shoot-outs will be
>+performed.
>+Then, each penalty trial is performed with the following procedure.
>+ 
>+\begin{enumerate}
>+\item The striker is defined as the robot from the striker's team with the
>+  lowest ID without a red card.
>+\item The goalkeeper is chosen based on the GameController information.
>+\item Both players are spawned at appropriate locations.
>+\item State is set to SET
>+\item Ball is spawned on the penalty mark.
>+\item The referee waits 15 seconds before sending signals to start the trial
>
>The referee waits 15 seconds before starting the trial
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <RoboCup-Humanoid-TC/Rules/pull/26/review/870532901 @ github . com> 
 
 
--
A B
Отправлено из Почты  Mail.ru
 

2022-02-07 12:38 UTC, MaikePaetzel commented
I don't see the commit that resolves these issues?

2022-02-24 17:56 UTC, MaikePaetzel commented
According to the rule vote on G01Q15, this received a majority of the votes and this PR will hence be merged.

2022-02-24 17:56 UTC, merged